DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS tokens;

CREATE TABLE scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  score INTEGER NOT NULL
);

CREATE TABLE tokens (
  token TEXT NOT NULL
);